# Practical Exam: Loan Insights

EasyLoan offers a wide range of loan services, including personal loans, car loans, and mortgages.

EasyLoan offers loans to clients from Canada, United Kingdom and United States.

The analytics team wants to report performance across different geographic areas. They aim to identify areas of strength and weakness for the business strategy team.

They need your help to ensure the data is accessible and reliable before they start reporting.


**Database Schema**

The data you need is in the database named `lending`.

![lending schema](./lending_schema.png)

In [10]:
import pandas as pd 

df_client = pd.read_csv('./exported/public.client.csv')
df_contract = pd.read_csv('./exported/public.contract.csv')
df_loan = pd.read_csv('./exported/public.loan.csv')
df_repayment = pd.read_csv('./exported/public.repayment.csv')

In [42]:
df_client.head()

   index  client_id            date_of_birth employment_status country
0      0          1  1963-07-08T00:00:00.000        unemployed     USA
1      1          2  1957-02-07T00:00:00.000        unemployed      UK
2      2          3  1993-02-21T00:00:00.000         Emplouyed      CA
3      3          4  1978-03-19T00:00:00.000          employed      CA
4      4          5  2000-10-02T00:00:00.000         Emplouyed     USA

In [50]:
print("Client Dataset Shape:", df_client.shape)
print("\nClient Data Types:")
print(df_client.dtypes)
print("\nClient Missing Values:")
print(df_client.isnull().sum())
print("\nClient Statistical Summary:")
print(df_client.describe())
print("\nUnique Values per Column:")
print(df_client.nunique())
print("\nEmployment Status Distribution:")
print(df_client['employment_status'].value_counts())
print("\nCountry Distribution:")
print(df_client['country'].value_counts())

Client Dataset Shape: (300, 5)

Client Data Types:
index                 int64
client_id             int64
date_of_birth        object
employment_status    object
country              object
dtype: object

Client Missing Values:
index                0
client_id            0
date_of_birth        0
employment_status    0
country              0
dtype: int64

Client Statistical Summary:
            index   client_id
count  300.000000  300.000000
mean   149.500000  150.500000
std     86.746758   86.746758
min      0.000000    1.000000
25%     74.750000   75.750000
50%    149.500000  150.500000
75%    224.250000  225.250000
max    299.000000  300.000000

Unique Values per Column:
index                300
client_id            300
date_of_birth        298
employment_status      5
country                3
dtype: int64

Employment Status Distribution:
employment_status
employed      136
unemployed    132
Full-time      14
Emplouyed      11
Part-time       7
Name: count, dtype: int64

Country Distribution:
country
USA    111
UK      97
CA      92
Name: count, dtype: int64

In [51]:
df_contract.head()

   index  contract_id            contract_date
0      0            1  2021-04-25T00:00:00.000
1      1            2  2021-05-11T00:00:00.000
2      2            3  2021-12-29T00:00:00.000
3      3            4  2022-03-24T00:00:00.000
4      4            5  2021-09-16T00:00:00.000

In [58]:
print("Contract Dataset Shape:", df_contract.shape)
print("\nContract Data Types:")
print(df_contract.dtypes)
print("\nContract Missing Values:")
print(df_contract.isnull().sum())
print("\nContract Statistical Summary:")
print(df_contract.describe())
print("\nContract Date Range:")
print(f"Min: {df_contract['contract_date'].min()}, Max: {df_contract['contract_date'].max()}")
print("\nDuplicate contract_ids:", df_contract['contract_id'].duplicated().sum())

Contract Dataset Shape: (500, 3)

Contract Data Types:
index             int64
contract_id       int64
contract_date    object
dtype: object

Contract Missing Values:
index            0
contract_id      0
contract_date    0
dtype: int64

Contract Statistical Summary:
            index  contract_id
count  500.000000   500.000000
mean   249.500000   250.500000
std    144.481833   144.481833
min      0.000000     1.000000
25%    124.750000   125.750000
50%    249.500000   250.500000
75%    374.250000   375.250000
max    499.000000   500.000000

Contract Date Range:
Min: 2021-04-16T00:00:00.000, Max: 2022-04-15T00:00:00.000

Duplicate contract_ids: 0

In [52]:
df_loan.head()

,index,loan_id,client_id,contract_id,principal_amount,interest_rate,loan_type
0,0,1,2,359,133143,0.02,car
1,1,2,235,106,154242,0.34,personal
2,2,3,117,120,45256,0.19,car
3,3,4,149,239,70487,0.13,car
4,4,5,11,23,55389,0.19,car

In [59]:
print("Loan Dataset Shape:", df_loan.shape)
print("\nLoan Data Types:")
print(df_loan.dtypes)
print("\nLoan Missing Values:")
print(df_loan.isnull().sum())
print("\nLoan Statistical Summary:")
print(df_loan.describe())
print("\nLoan Type Distribution:")
print(df_loan['loan_type'].value_counts())
print("\nInterest Rate Statistics:")
print(df_loan['interest_rate'].describe())
print("\nPrincipal Amount Statistics:")
print(df_loan['principal_amount'].describe())

Loan Dataset Shape: (1000, 7)

Loan Data Types:
index                 int64
loan_id               int64
client_id             int64
contract_id           int64
principal_amount      int64
interest_rate       float64
loan_type            object
dtype: object

Loan Missing Values:
index               0
loan_id             0
client_id           0
contract_id         0
principal_amount    0
interest_rate       0
loan_type           0
dtype: int64

Loan Statistical Summary:
             index      loan_id    client_id  contract_id  principal_amount  \
count  1000.000000  1000.000000  1000.000000  1000.000000       1000.000000
mean    499.500000   500.500000   148.551000   247.794000     104599.846000
std     288.819436   288.819436    86.424305   145.149992      54966.652885
min       0.000000     1.000000     1.000000     1.000000      10400.000000
25%     249.750000   250.750000    72.750000   124.000000      57470.750000
50%     499.500000   500.500000   147.000000   245.000000     104873.500000
75%     749.250000   750.250000   222.250000   374.250000     151925.250000
max     999.000000  1000.000000   300.000000   500.000000     199777.000000

       interest_rate
count    1000.000000
mean        0.119380
std         0.090016
min         0.020000
25%         0.050000
50%         0.080000
75%         0.170000
max         0.360000

Loan Type Distribution:
loan_type
mortgage    346
personal    330
car         324
Name: count, dtype: int64

Interest Rate Statistics:
count    1000.000000
mean        0.119380
std         0.090016
min         0.020000
25%         0.050000
50%         0.080000
75%         0.170000
max         0.360000
Name: interest_rate, dtype: float64

Principal Amount Statistics:
count      1000.000000
mean     104599.846000
std       54966.652885
min       10400.000000
25%       57470.750000
50%      104873.500000
75%      151925.250000
max      199777.000000
Name: principal_amount, dtype: float64

In [60]:
df_repayment.head()

,index,repayment_id,loan_id,repayment_date,repayment_amount,repayment_channel
0,0,1,357,2022-10-16T00:00:00.000,1675.83,bank account
1,1,2,805,2023-01-12T00:00:00.000,867.22,debit card
2,2,3,843,2022-06-02T00:00:00.000,718.83,phone
3,3,4,243,2022-12-26T00:00:00.000,1620.97,credit card
4,4,5,991,2023-03-18T00:00:00.000,2182.17,phone

In [65]:
print("Repayment Dataset Shape:", df_repayment.shape)
print("\nRepayment Data Types:")
print(df_repayment.dtypes)
print("\nRepayment Missing Values:")
print(df_repayment.isnull().sum())
print("\nRepayment Statistical Summary:")
print(df_repayment.describe())
print("\nRepayment Channel Distribution:")
print(df_repayment['repayment_channel'].value_counts())
print("\nRepayment Amount Statistics:")
print(df_repayment['repayment_amount'].describe())
print("\nRepayments with '-' channel:", (df_repayment['repayment_channel'] == '-').sum())
print("\nRepayment Date Range:")
print(f"Min: {df_repayment['repayment_date'].min()}, Max: {df_repayment['repayment_date'].max()}")

Repayment Dataset Shape: (1500, 6)

Repayment Data Types:
index                  int64
repayment_id           int64
loan_id                int64
repayment_date        object
repayment_amount     float64
repayment_channel     object
dtype: object

Repayment Missing Values:
index                0
repayment_id         0
loan_id              0
repayment_date       0
repayment_amount     0
repayment_channel    0
dtype: int64

Repayment Statistical Summary:
             index  repayment_id      loan_id  repayment_amount
count  1500.000000   1500.000000  1500.000000       1500.000000
mean    749.500000    750.500000   499.024667       1578.546313
std     433.157015    433.157015   290.151172       1130.084741
min       0.000000      1.000000     1.000000        277.830000
25%     374.750000    375.750000   249.750000        651.847500
50%     749.500000    750.500000   494.500000       1265.655000
75%    1124.250000   1125.250000   750.250000       2254.292500
max    1499.000000   1500.000000  1000.000000       5284.890000

Repayment Channel Distribution:
repayment_channel
phone           292
mail            288
credit card     277
debit card      272
bank account    245
-               126
Name: count, dtype: int64

Repayment Amount Statistics:
count    1500.000000
mean     1578.546313
std      1130.084741
min       277.830000
25%       651.847500
50%      1265.655000
75%      2254.292500
max      5284.890000
Name: repayment_amount, dtype: float64

Repayments with '-' channel: 126

Repayment Date Range:
Min: 2022-04-16T00:00:00.000, Max: 2023-04-16T00:00:00.000

---

# Task 1 

The analytics team wants to use the `client` table to create a dashboard for client details. For them to proceed, they need to be sure the data is clean enough to use.

The `client` table below illustrates what the analytics team expects the data types and format to be.

Write an SQL query that returns the `client` table with the specified format, including identifying and cleaning all invalid values. 
-  Your output should be a DataFrame with the name 'client'. Do not modify the `client` table.
-  Note that the DataLab environment formats dates as YYYY-MM-DD-hh-ss-SSS. 

| Column Name       | Description                                                      |
|-------------------|------------------------------------------------------------------|
| client_id         | Unique integer (set by the database, can’t take any other value) |
| date\_of\_birth       | Date of birth of the client, as a date                           |
| employment_status        | Current employment status of the client, either employed or unemployed, as a lower case string                              |
| country          | The country where the client resides, either USA, UK or CA, as an upper case string                      |

Query:

```sql
SELECT 
    client_id,
    CAST(date_of_birth AS DATE) AS date_of_birth,
    CASE
        WHEN LOWER(employment_status) = 'unemployed' THEN 'unemployed'
        ELSE 'employed'
    END AS employment_status,
    UPPER(country) AS country
FROM client;
```

In [66]:
import pandas as pd 

df = pd.read_csv('./exported/task1_exported.csv')

df.head(300)

     index  client_id            date_of_birth employment_status country
0        0          1  1963-07-08T00:00:00.000        unemployed     USA
1        1          2  1957-02-07T00:00:00.000        unemployed      UK
2        2          3  1993-02-21T00:00:00.000          employed      CA
3        3          4  1978-03-19T00:00:00.000          employed      CA
4        4          5  2000-10-02T00:00:00.000          employed     USA
..     ...        ...                      ...               ...     ...
295    295        296  1963-05-02T00:00:00.000          employed      CA
296    296        297  2004-08-25T00:00:00.000          employed      UK
297    297        298  1997-08-03T00:00:00.000        unemployed      UK
298    298        299  2004-08-16T00:00:00.000        unemployed      CA
299    299        300  1965-03-02T00:00:00.000          employed     USA

[300 rows x 5 columns]

---

# Task 2

You have been told that there was a problem in the backend system as some of the `repayment_channel` values are missing. 

The missing values are critical to the analysis so they need to be filled in before proceeding.

Luckily, they have discovered a pattern in the missing values:

- Repayment higher than 4000 dollars should be made via `bank account`.
- Repayment lower than 1000 dollars should be made via `mail`.

Write an SQL query that makes the `repayment` table match these criteria.
-  Your output should be a DataFrame with the name 'repayment'. Do not modify the original `repayment` table.

Query:

```sql
SELECT
  repayment_id,
  loan_id,
  repayment_date,
  repayment_amount,
  CASE
    WHEN repayment_channel = '-' AND repayment_amount > 4000 THEN 'bank account'
    WHEN repayment_channel = '-' AND repayment_amount < 1000 THEN 'mail'
    ELSE repayment_channel
  END AS repayment_channel
FROM repayment;
```

In [67]:
import pandas as pd

df = pd.read_csv('./exported/task2_exported.csv')

df.head(1500)

,index,repayment_id,loan_id,repayment_date,repayment_amount,repayment_channel
0,0,1,357,2022-10-16T00:00:00.000,1675.83,bank account
1,1,2,805,2023-01-12T00:00:00.000,867.22,debit card
2,2,3,843,2022-06-02T00:00:00.000,718.83,phone
3,3,4,243,2022-12-26T00:00:00.000,1620.97,credit card
4,4,5,991,2023-03-18T00:00:00.000,2182.17,phone
...,...,...,...,...,...,...
1495,1495,1496,192,2023-02-11T00:00:00.000,2506.47,debit card
1496,1496,1497,999,2022-11-21T00:00:00.000,1324.61,bank account
1497,1497,1498,966,2023-01-26T00:00:00.000,1375.81,debit card
1498,1498,1499,20,2023-03-30T00:00:00.000,1231.25,debit card
1499,1499,1500,560,2022-04-21T00:00:00.000,361.11,mail

---

# Task 3

Starting on January 1st, 2022, all US clients started to use an online system to sign contracts.

The analytics team wants to analyze the loans for US clients who used the new online system.

Write a query that returns the data for the analytics team. Your output should include `client_id`,`contract_date`, `principal_amount` and `loan_type` columns.

![database schema](lending_schema.png)

Query:

```sql
SELECT
    client.client_id,
    contract.contract_date,
    loan.principal_amount,
    loan.loan_type
FROM client
JOIN loan ON client.client_id = loan.client_id
JOIN contract ON loan.contract_id = contract.contract_id
WHERE client.country = 'USA' AND contract.contract_date >= '2022-01-01';
```

In [68]:
import pandas as pd

df = pd.read_csv('./exported/task3_exported.csv')

df.head(100)

    index  client_id            contract_date  principal_amount loan_type
0       0        267  2022-03-08T00:00:00.000            179230  personal
1       1         50  2022-01-13T00:00:00.000            143729  mortgage
2       2        280  2022-01-02T00:00:00.000            171122       car
3       3         79  2022-01-24T00:00:00.000             43784  mortgage
4       4        245  2022-01-03T00:00:00.000             95003  mortgage
..    ...        ...                      ...               ...       ...
89     89          8  2022-01-13T00:00:00.000            148282  personal
90     90        232  2022-02-08T00:00:00.000             78386  personal
91     91         95  2022-03-20T00:00:00.000             39098  personal
92     92        123  2022-03-06T00:00:00.000             48213       car
93     93        211  2022-02-23T00:00:00.000            147004  mortgage

[94 rows x 5 columns]

---

# Task 4

The business strategy team is considering offering a more competitive rate to the US market. 

The analytic team want to compare the average interest rates offered by the company for the same loan type in different countries to determine if there are significant differences.

Write a query that returns the data for the analytics team. Your output should include `loan_type`, `country` and `avg_rate` columns.

![database schema](lending_schema.png)

Query:

```sql
SELECT
    l.loan_type,
    c.country,
    AVG(l.interest_rate) AS avg_rate
FROM loan AS l
JOIN client AS c ON l.client_id = c.client_id
GROUP BY l.loan_type, c.country
ORDER BY l.loan_type, country;
```

In [69]:
import pandas as pd

df = pd.read_csv('./exported/task4_exported.csv')

df.head(10)

   index loan_type country  avg_rate
0      0       car      CA  0.112039
1      1       car      UK  0.122613
2      2       car     USA  0.103636
3      3  mortgage      CA  0.044068
4      4  mortgage      UK  0.042281
5      5  mortgage     USA  0.043860
6      6  personal      CA  0.217253
7      7  personal      UK  0.198738
8      8  personal     USA  0.202721